// tslint:disable:max-line-length
export const MessageTranslations = {
    en: {
        'en': 'English',
        'ru': 'Russian',
        'MESSAGE.BREADCRUMB.TITLE': 'Message templates',
        'MESSAGE.CREATE': 'Messages templates create',
        'MESSAGE.UPDATE': 'Messages templates update',
        'MESSAGE.EDIT' : 'Edit message',
        'MESSAGE.VIEW': 'View message',
        'MESSAGE.EMPTY': 'Messages templates not found',
        'MESSAGE.EMPTY.SUBTEXT': 'Message templates allow you to change the contents of system messages. The identifier serves as a key for finding the required template. Parameters allow you to insert variable values into the message. To find out what parameters are supported in each particular message, refer to the documentation.',
        'MESSAGE.CREATE.NEW.TITLE': 'Messages template name',
        'MESSAGE.CREATE.NEW.SUBTITLE': 'Messages template status',
        'MESSAGE.ADD.BUTTON.TEXT': 'Add message template',
        'MESSAGE.LOADING': 'Loading messages',
        'MESSAGE.VIEW.SAVE.TEXT': 'Save',
        'MESSAGE.VIEW.BUTTON.CANCEL.TEXT': 'Cancel',
        'MESSAGE.VIEW.EDIT.TITLE.TEXT': 'Edit message',
        'MESSAGE.VIEW.CREATE.TITLE.TEXT': 'Create message',
        'MESSAGE.VIEW.CREATE.TEXT': 'Create',
        'MESSAGE.VIEW.EDIT.MESSAGE.TEXT': 'Message',
        'MESSAGE.VIEW.DELETE.TEXT': 'Delete',
        'MESSAGE.VIEW.TEXT.TEXT': 'Text',
        'MESSAGE.VIEW.HTML.TEXT': 'Html',
        'MESSAGE.DETAILS': 'Details',
        'MESSAGE.VIEW.REVIEW.BUTTON.LABEL': 'Review',
        'MESSAGE_STATUS_NEW': 'New',
        'MESSAGE_STATUS_WRITING': 'Writing',
        'MESSAGE_STATUS_TRANSLATING': 'Translating',
        'MESSAGE_STATUS_VERIFYING': 'Verifying',
        'MESSAGE_STATUS_COMPLETED': 'Completed',
        'MESSAGE.VIEW.NAME.LABEL': 'Name',
        'MESSAGE.VIEW.STATUS.LABEL': 'Status',
        'MESSAGE.VIEW.STATUS.SUBJECT': 'Subject',
        'MESSAGE.UPDATE.ERROR.NAME.REQUIRED': 'Name is required',
        'MESSAGE.DELETE.DIALOG.MESSAGE': 'Do you agree?',
        'MESSAGE.DELETE.DIALOG.TITLE': 'Delete message',
        'MESSAGE.DELETE.DIALOG.BUTTON.CANCEL': 'Disagree',
        'MESSAGE.DELETE.DIALOG.BUTTON.OK': 'Agree',
        'MESSAGE.EDIT.CANCEL.DIALOG.MESSAGE': 'Your changes have not been saved. Selecting another entry will cancel the changes. Continue?',
        'MESSAGE.EDIT.CANCEL.DIALOG.TITLE': 'Warning',
        'MESSAGE.EDIT.CANCEL.DIALOG.BUTTON.CANCEL': 'Cancel',
        'MESSAGE.EDIT.CANCEL.DIALOG.BUTTON.OK': 'Continue'
    },
    ru: {
        'en': 'Английский',
        'ru': 'Русский',
        'MESSAGE.BREADCRUMB.TITLE': 'Шаблоны сообщений',
        'MESSAGE.EDIT' : 'Редактирование',
        'MESSAGE.VIEW': 'Просмотр',
        'MESSAGE.EMPTY': 'Шаблоны сообщений отутствуют',
        'MESSAGE.EMPTY.SUBTEXT': 'Шаблоны сообщений позволяют менять содержание системных сообщений. Идентификатор служит ключем для поиска требуемого шаблона. Параметры позволяют вставлять в сообщение изменяемые значения. Чтобы узнать какие параметры поддерживаются в каждом конкретном сообщении обратитесь к документации.',
        'MESSAGE.CREATE.NEW.TITLE': 'Название шаблона собщения',
        'MESSAGE.CREATE.NEW.SUBTITLE': 'Статус шаблона сообщения',
        'MESSAGE.ADD.BUTTON.TEXT': 'Добавить шаблон сообщения',
        'MESSAGE.LOADING': 'Загрузка шаблонов сообщений',
        'MESSAGE.CREATE': 'Создание нового шаблона',
        'MESSAGE.UPDATE': 'Редактирование шаблона',
        'MESSAGE.VIEW.SAVE.TEXT': 'Сохранить',
        'MESSAGE.VIEW.BUTTON.CANCEL.TEXT': 'Отменить',
        'MESSAGE.VIEW.CREATE.TEXT': 'Создать',
        'MESSAGE.VIEW.EDIT.TITLE.TEXT': 'Изменение шаблона',
        'MESSAGE.VIEW.CREATE.TITLE.TEXT': 'Создать новый шаблон',
        'MESSAGE.VIEW.EDIT.MESSAGE.TEXT': 'Сообщение',
        'MESSAGE.VIEW.DELETE.TEXT': 'Удалить',
        'MESSAGE.VIEW.TEXT.TEXT': 'Текст',
        'MESSAGE.VIEW.HTML.TEXT': 'Html',
        'MESSAGE.DETAILS': 'Подробно',
        'MESSAGE.VIEW.REVIEW.BUTTON.LABEL': 'Предв. просмотр',
        'MESSAGE_STATUS_NEW': 'Новый',
        'MESSAGE_STATUS_WRITING': 'Написан',
        'MESSAGE_STATUS_TRANSLATING': 'Переведен',
        'MESSAGE_STATUS_VERIFYING': 'Проверен',
        'MESSAGE_STATUS_COMPLETED': 'Закончен',
        'MESSAGE.VIEW.NAME.LABEL': 'Имя',
        'MESSAGE.VIEW.STATUS.LABEL': 'Статус',
        'MESSAGE.VIEW.STATUS.SUBJECT': 'Назначение',
        'MESSAGE.UPDATE.ERROR.NAME.REQUIRED': 'Введите наименование шаблона сообщения',
        'MESSAGE.DELETE.DIALOG.MESSAGE': 'Вы уверены?',
        'MESSAGE.DELETE.DIALOG.TITLE': 'Удалить сообщение',
        'MESSAGE.DELETE.DIALOG.BUTTON.CANCEL': 'Отменить',
        'MESSAGE.DELETE.DIALOG.BUTTON.OK': 'Удалить',
        'MESSAGE.EDIT.CANCEL.DIALOG.MESSAGE': 'Изменения не сохранены. Переход на другую запись приведет к отмене сделанных изменений. Продолжить?',
        'MESSAGE.EDIT.CANCEL.DIALOG.TITLE': 'Предупреждение',
        'MESSAGE.EDIT.CANCEL.DIALOG.BUTTON.CANCEL': 'Отмена',
        'MESSAGE.EDIT.CANCEL.DIALOG.BUTTON.OK': 'Продолжить'
    }
};
